# Data Cleaning

## Necessary Packages

In [1]:
import pandas as pd
import numpy as np

## Dataset Load

In [2]:
# Load raw datasets
fangraphs_raw = pd.read_csv("../Data/Raw/FanGraphs_Raw.csv")
statcast_raw = pd.read_csv("../Data/Raw/Statcast_Raw.csv")

## Column Name Formatting

In [3]:
# Define a function to standardize column names
def standardize_columns(df):
    df.columns = (df.columns
                  .str.strip()
                  .str.lower()
                  .str.replace(" ", "_")
                  .str.replace("%", "pct")
                  .str.replace("/", "_")
                  .str.replace("-", "_")
                  .str.replace("(", "")
                  .str.replace(")", ""))
    return df

# Call the standardization function on each dataset
fangraphs_raw = standardize_columns(fangraphs_raw)
statcast_raw = standardize_columns(statcast_raw)

# Display some column names for verification
print("Some clean column names from the FanGraphs dataset:\n")
print(fangraphs_raw.columns[:25], "\n\n")
print("Some clean column names from the Statcast dataset:\n")
print(statcast_raw.columns[:25])

Some clean column names from the FanGraphs dataset:

Index(['fangraphs_id', 'season', 'name', 'team', 'age', 'g', 'ab', 'pa', 'h',
       '1b', '2b', '3b', 'hr', 'r', 'rbi', 'bb', 'ibb', 'so', 'hbp', 'sf',
       'sh', 'gdp', 'sb', 'cs', 'avg'],
      dtype='object')


Some clean column names from the Statcast dataset:

Index(['last_name,_first_name', 'player_id', 'attempts', 'avg_hit_angle',
       'anglesweetspotpercent', 'max_hit_speed', 'avg_hit_speed', 'ev50',
       'fbld', 'gb', 'max_distance', 'avg_distance', 'avg_hr_distance',
       'ev95plus', 'ev95percent', 'barrels', 'brl_percent', 'brl_pa',
       'season'],
      dtype='object')

## Names of Relevant Columns in FanGraphs Dataset

In [4]:
# There are many relevant columns that must, unfortunately, be renamed manually
fangraphs_raw = fangraphs_raw.rename(
    columns = {
        "name": "player_name",                     
        "g": "games_played",
        "ab": "at_bats",
        "pa": "plate_appearances",
        "h": "hits",
        "1b": "singles",
        "2b": "doubles",
        "3b": "triples",
        "hr": "home_runs",
        "r": "runs",
        "rbi": "runs_batted_in",
        "bb": "walks",
        "ibb": "intentional_walks",
        "so": "strikeouts",
        "hbp": "hit_by_pitch",
        "sb": "stolen_bases",
        "cs": "caught_stealing",
        "avg": "batting_average",
        "obp": "on_base_percentage",
        "slg": "slugging_percentage",
        "ops": "on_base_plus_slugging",
        "iso": "isolated_power",
        "babip": "batting_average_on_balls_in_play",
        "bbpct": "walk_percentage",
        "kpct": "strikeout_percentage",
        "bb_k": "walks_to_strikeouts_ratio",
        "o_swingpct": "outside_swing_percentage",
        "z_swingpct": "zone_swing_percentage",
        "swingpct": "swing_percentage",
        "o_contactpct": "outside_contact_percentage",
        "z_contactpct": "zone_contact_percentage",
        "contactpct": "contact_percentage",
        "zonepct": "zone_percentage",
        "f_strikepct": "first_pitch_strike_percentage",
        "swstrpct": "swinging_strike_percentage",
        "gb": "ground_balls",
        "fb": "fly_balls",
        "ld": "line_drives",
        "iffb": "infield_fly_balls",
        "gbpct": "ground_ball_percentage",
        "ldpct": "line_drive_percentage",
        "fbpct": "fly_ball_percentage",
        "iffbpct": "infield_fly_ball_percentage",
        "hr_fb": "home_run_fly_ball_percentage",
        "pullpct": "pull_percentage",
        "centpct": "center_percentage",
        "oppopct": "oppo_percentage",
        "softpct": "soft_hit_percentage",
        "medpct": "medium_hit_percentage",
        "hardpct": "hard_hit_percentage",
        "woba": "weighted_on_base_average",
        "wraa": "weighted_runs_above_average",
        "wrc": "weighted_runs_created",
        "wrc+": "weighted_runs_created_plus",
        "rar": "runs_above_replacement",
        "war": "wins_above_replacement",
        "spd": "speed_score",
        "bsr": "base_running_score",
        "ubr": "ultimate_base_running_score",
        "ev": "average_exit_velocity",
        "la": "average_launch_angle",
        "barrels": "barrels",
        "barrelpct": "barrel_percentage",
        "maxev": "maximum_exit_velocity",
        "cstrpct": "called_strike_percentage",
        "cswpct": "called_strike_whiff_percentage",
        "xba": "expected_batting_average",
        "xslg": "expected_slugging_percentage",
        "xwoba": "expected_weighted_on_base_average"
               }
                                     )

## Smaller Version of FanGraphs Dataset with Only Relevant Columns

In [5]:
# Core identifiers
id_cols = ["fangraphs_id", 
           "mlbam_id", 
           "season", 
           "player_name", 
           "team"]

# Counting stats
counting = ["games_played", 
            "at_bats", 
            "plate_appearances", 
            "hits", 
            "singles", 
            "doubles", 
            "triples", 
            "home_runs", 
            "runs", 
            "runs_batted_in", 
            "walks", 
            "intentional_walks", 
            "strikeouts", 
            "hit_by_pitch", 
            "stolen_bases", 
            "caught_stealing"]

# Traditional rate stats
traditional_rate = ["batting_average", 
                    "on_base_percentage", 
                    "slugging_percentage", 
                    "on_base_plus_slugging", 
                    "isolated_power", 
                    "batting_average_on_balls_in_play"]

# Plate discipline
discipline = ["walk_percentage", 
              "strikeout_percentage", 
              "walks_to_strikeouts_ratio",
              "outside_swing_percentage", 
              "zone_swing_percentage", 
              "swing_percentage",
              "outside_contact_percentage", 
              "zone_contact_percentage", 
              "contact_percentage", 
              "zone_percentage", 
              "first_pitch_strike_percentage", 
              "swinging_strike_percentage"]

# Batted-ball profile
batted_ball = ["ground_balls", 
               "fly_balls", 
               "line_drives",
               "infield_fly_balls",
               "ground_ball_percentage", 
               "line_drive_percentage",
               "fly_ball_percentage", 
               "infield_fly_ball_percentage",
               "home_run_fly_ball_percentage", 
               "pull_percentage", 
               "center_percentage", 
               "oppo_percentage", 
               "soft_hit_percentage", 
               "medium_hit_percentage", 
               "hard_hit_percentage"]

# Value stats
value_stats = ["weighted_on_base_average", 
               "weighted_runs_above_average",
               "weighted_runs_created", 
               "weighted_runs_created_plus",
               "runs_above_replacement", 
               "wins_above_replacement", 
               "speed_score", 
               "base_running_score", 
               "ultimate_base_running_score"]

# Statcast-related columns
statcast_related = ["average_exit_velocity", 
                    "average_launch_angle", 
                    "barrels", 
                    "barrel_percentage",
                    "maximum_exit_velocity", 
                    "called_strike_percentage", 
                    "called_strike_whiff_percentage", 
                    "expected_batting_average", 
                    "expected_slugging_percentage", 
                    "expected_weighted_on_base_average"]

# Create the final keep list
fangraphs_keep_cols = (id_cols + counting + traditional_rate +
                       discipline + batted_ball + value_stats +
                       statcast_related)

# Create the smaller dataset
fangraphs_raw = fangraphs_raw[fangraphs_keep_cols]
print(f"Shape of the smaller FanGraphs dataset: {fangraphs_raw.shape}\n")
fangraphs_raw.head()

Shape of the smaller FanGraphs dataset: (2500, 73)

,fangraphs_id,mlbam_id,season,player_name,team,games_played,at_bats,plate_appearances,hits,singles,...,average_exit_velocity,average_launch_angle,barrels,barrel_percentage,maximum_exit_velocity,called_strike_percentage,called_strike_whiff_percentage,expected_batting_average,expected_slugging_percentage,expected_weighted_on_base_average
0,15640,592450,2017,Aaron Judge,NYY,155,542,678,154,75,...,95.0,15.8,87.0,0.257,121.1,0.157,0.290,0.287,0.668,0.450
1,5417,514888,2017,Jose Altuve,HOU,153,590,662,204,137,...,86.1,9.7,34.0,0.067,109.1,0.161,0.233,0.291,0.477,0.360
2,13510,608070,2017,Jose Ramirez,CLE,152,585,645,186,95,...,88.2,15.0,26.0,0.050,108.3,0.177,0.231,0.303,0.488,0.361
3,15429,592178,2017,Kris Bryant,CHC,151,549,665,162,91,...,87.0,17.0,41.0,0.096,113.0,0.138,0.239,0.260,0.497,0.376
4,10155,545361,2017,Mike Trout,LAA,114,402,507,123,62,...,88.8,18.0,42.0,0.133,114.7,0.193,0.255,0.294,0.589,0.424

## Names of Relevant Columns in Statcast Dataset

In [6]:
# Again, these relevant columns must be renamed manually
statcast_raw = statcast_raw.rename(
    columns = {
        "player_id": "mlbam_id",  # This is a duplicate but will be kept for merging
        "anglesweetspotpercent": "sweet_spot_percentage", 
        "fbld": "fly_ball_line_drive_average_exit_velocity",
        "gb": "ground_ball_average_exit_velocity",
        "max_distance": "maximum_distance_hit",
        "avg_distance": "average_distance_hit",
        "avg_hr_distance": "average_home_run_distance",
        "ev95plus": "exit_velocity_95_mph_plus_count",
        "brl_pa": "barrels_per_plate_appearance_percentage",
               }
                                    )

## Smaller Version of Statcast Dataset with Only Relevant Columns

In [7]:
# Create the final keep list
statcast_keep_cols = ["mlbam_id", 
                      "season",  # This is a duplicate but will be kept for merging 
                      "sweet_spot_percentage",
                      "fly_ball_line_drive_average_exit_velocity", 
                      "ground_ball_average_exit_velocity",
                      "maximum_distance_hit", 
                      "average_distance_hit", 
                      "average_home_run_distance", 
                      "exit_velocity_95_mph_plus_count", 
                      "barrels_per_plate_appearance_percentage"]

# Create the smaller dataset
statcast_raw = statcast_raw[statcast_keep_cols]
print(f"Shape of the smaller Statcast dataset: {statcast_raw.shape}\n")
statcast_raw.head()

Shape of the smaller Statcast dataset: (1746, 10)

,mlbam_id,season,sweet_spot_percentage,fly_ball_line_drive_average_exit_velocity,ground_ball_average_exit_velocity,maximum_distance_hit,average_distance_hit,average_home_run_distance,exit_velocity_95_mph_plus_count,barrels_per_plate_appearance_percentage
0,542255,2017,34.3,87.5,78.7,434,152,382.0,75,0.4
1,543829,2017,27.7,85.9,79.6,395,123,380.0,63,0.1
2,596019,2017,32.2,92.8,85.4,456,192,401.0,203,5.5
3,605141,2017,31.9,92.9,87.4,434,179,396.0,208,3.5
4,466320,2017,33.6,90.9,87.5,420,161,393.0,194,3.2

## FanGraphs and Statcast Merge

In [8]:
# Merge on shared keys
fangraphs_statcast_raw = fangraphs_raw.merge(statcast_raw,
                                             how = "left",
                                             on = ["mlbam_id", "season"])
print(f"Shape of the merged dataset: {fangraphs_statcast_raw.shape}\n")
fangraphs_statcast_raw.head()

Shape of the merged dataset: (2500, 81)

,fangraphs_id,mlbam_id,season,player_name,team,games_played,at_bats,plate_appearances,hits,singles,...,expected_slugging_percentage,expected_weighted_on_base_average,sweet_spot_percentage,fly_ball_line_drive_average_exit_velocity,ground_ball_average_exit_velocity,maximum_distance_hit,average_distance_hit,average_home_run_distance,exit_velocity_95_mph_plus_count,barrels_per_plate_appearance_percentage
0,15640,592450,2017,Aaron Judge,NYY,155,542,678,154,75,...,0.668,0.450,38.2,100.5,88.6,496.0,216.0,413.0,185.0,12.8
1,5417,514888,2017,Jose Altuve,HOU,153,590,662,204,137,...,0.477,0.360,34.8,91.3,82.2,430.0,167.0,393.0,143.0,5.1
2,13510,608070,2017,Jose Ramirez,CLE,152,585,645,186,95,...,0.488,0.361,35.5,91.9,85.2,440.0,185.0,391.0,180.0,4.0
3,15429,592178,2017,Kris Bryant,CHC,151,549,665,162,91,...,0.497,0.376,35.1,92.3,80.5,451.0,196.0,401.0,156.0,6.2
4,10155,545361,2017,Mike Trout,LAA,114,402,507,123,62,...,0.589,0.424,36.4,94.3,84.1,448.0,199.0,411.0,126.0,8.3

## Missing Values

In [9]:
# Drop rows with missing values
fangraphs_statcast_raw = fangraphs_statcast_raw.dropna()
print(f"Shape of the merged dataset after dropping missing values: {fangraphs_statcast_raw.shape}\n")
fangraphs_statcast_raw.head()

Shape of the merged dataset after dropping missing values: (1706, 81)

,fangraphs_id,mlbam_id,season,player_name,team,games_played,at_bats,plate_appearances,hits,singles,...,expected_slugging_percentage,expected_weighted_on_base_average,sweet_spot_percentage,fly_ball_line_drive_average_exit_velocity,ground_ball_average_exit_velocity,maximum_distance_hit,average_distance_hit,average_home_run_distance,exit_velocity_95_mph_plus_count,barrels_per_plate_appearance_percentage
0,15640,592450,2017,Aaron Judge,NYY,155,542,678,154,75,...,0.668,0.450,38.2,100.5,88.6,496.0,216.0,413.0,185.0,12.8
1,5417,514888,2017,Jose Altuve,HOU,153,590,662,204,137,...,0.477,0.360,34.8,91.3,82.2,430.0,167.0,393.0,143.0,5.1
2,13510,608070,2017,Jose Ramirez,CLE,152,585,645,186,95,...,0.488,0.361,35.5,91.9,85.2,440.0,185.0,391.0,180.0,4.0
3,15429,592178,2017,Kris Bryant,CHC,151,549,665,162,91,...,0.497,0.376,35.1,92.3,80.5,451.0,196.0,401.0,156.0,6.2
4,10155,545361,2017,Mike Trout,LAA,114,402,507,123,62,...,0.589,0.424,36.4,94.3,84.1,448.0,199.0,411.0,126.0,8.3

## Datatypes

In [10]:
# Identify non-numeric columns 
non_numeric_cols = ["player_name", "team"]

# Convert everything else to numeric
for col in fangraphs_statcast_raw.columns:
    if col not in non_numeric_cols:
        fangraphs_statcast_raw[col] = pd.to_numeric(fangraphs_statcast_raw[col], errors = "coerce")

# Round all numeric columns to at most three decimal places
numeric_cols = fangraphs_statcast_raw.select_dtypes(include = ["number"]).columns
fangraphs_statcast_raw[numeric_cols] = fangraphs_statcast_raw[numeric_cols].round(3)

# Some columns require special handling (not in order below)
fangraphs_statcast_raw["sweet_spot_percentage"] = (fangraphs_statcast_raw["sweet_spot_percentage"] / 100).round(3)
fangraphs_statcast_raw["barrels_per_plate_appearance_percentage"] = (fangraphs_statcast_raw["barrels_per_plate_appearance_percentage"] / 100).round(3)
fangraphs_statcast_raw["exit_velocity_95_mph_plus_count"] = fangraphs_statcast_raw["exit_velocity_95_mph_plus_count"].astype(int)
fangraphs_statcast_raw["barrels"] = fangraphs_statcast_raw["barrels"].astype(int)
fangraphs_statcast_raw["maximum_distance_hit"] = fangraphs_statcast_raw["maximum_distance_hit"].astype(int)
fangraphs_statcast_raw["average_distance_hit"] = fangraphs_statcast_raw["average_distance_hit"].astype(int)
fangraphs_statcast_raw["average_home_run_distance"] = fangraphs_statcast_raw["average_home_run_distance"].astype(int)
fangraphs_statcast_raw["weighted_runs_created_plus"] = fangraphs_statcast_raw["weighted_runs_created_plus"].astype(int)

# Check result
fangraphs_statcast_raw.head()

,fangraphs_id,mlbam_id,season,player_name,team,games_played,at_bats,plate_appearances,hits,singles,...,expected_slugging_percentage,expected_weighted_on_base_average,sweet_spot_percentage,fly_ball_line_drive_average_exit_velocity,ground_ball_average_exit_velocity,maximum_distance_hit,average_distance_hit,average_home_run_distance,exit_velocity_95_mph_plus_count,barrels_per_plate_appearance_percentage
0,15640,592450,2017,Aaron Judge,NYY,155,542,678,154,75,...,0.668,0.450,0.382,100.5,88.6,496,216,413,185,0.128
1,5417,514888,2017,Jose Altuve,HOU,153,590,662,204,137,...,0.477,0.360,0.348,91.3,82.2,430,167,393,143,0.051
2,13510,608070,2017,Jose Ramirez,CLE,152,585,645,186,95,...,0.488,0.361,0.355,91.9,85.2,440,185,391,180,0.040
3,15429,592178,2017,Kris Bryant,CHC,151,549,665,162,91,...,0.497,0.376,0.351,92.3,80.5,451,196,401,156,0.062
4,10155,545361,2017,Mike Trout,LAA,114,402,507,123,62,...,0.589,0.424,0.364,94.3,84.1,448,199,411,126,0.083

## Final Tasks

In [11]:
# Remove ID columns that are no longer needed
final_cols = [col for col in fangraphs_statcast_raw.columns if col not in ["fangraphs_id", 
                                                                           "mlbam_id"]]
clean_dataset = fangraphs_statcast_raw[final_cols]

# Make a Judge-only dataset
judge_dataset = clean_dataset[clean_dataset["player_name"] == "Aaron Judge"].copy()

# Save the clean datasets
clean_dataset.to_csv("../Data/Clean/All_Players.csv", index = False)
judge_dataset.to_csv("../Data/Clean/Judge_Only.csv", index = False)